# Generated by Django 3.1.3 on 2020-12-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.CharField(default='123456', max_length=50),
            preserve_default=False,
        ),
    ]
